export default {
  CREATE_STUDENT: "CREATE_STUDENT",
  LOAD_STUDENTS: "LOAD_STUDENTS",
  LOAD_SINGLE_STUDENT: "LOAD_SINGLE_STUDENT",
  LOAD_STUDENT_NATIONALITY: "LOAD_STUDENT_NATIONALITY",
  LOAD_STUDENT_DETAILS: "LOAD_STUDENT_DETAILS",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  DELETE_FAMILY_MEMBER: "DELETE_FAMILY_MEMBER",
};
